### PR TITLE
[Feature] Copy the query diff result as image and save to clipboard

### PR DESCRIPTION
**Pull request by kentwelcome**
**PR checklist**

- [x] Ensure you have added or ran the appropriate tests for your PR.
- [x] DCO signed

**What type of PR is this?**
Feature

**What this PR does / why we need it**:
- Save query diff result as an image
- Save the image into clipboard
- Highlight the copied area when mouse hover the copy button

**Which issue(s) this PR fixes**:
RC-93

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

### CODE REVIEW

**Review by popcornylu — COMMENTED** [review]
It seems that it requires every check view add the screenoshot logic. Could we add this feature as container?

```
<ScreenshotBox>
   <QueryDataGrid />
</ScreenshotBox>
```

**Comment by kentwelcome** [comment]
> It seems that it requires every check view add the screenoshot logic. Could we add this feature as container?
> 
> ```
> <ScreenshotBox>
>    <QueryDataGrid />
> </ScreenshotBox>
> ```

Sure!

**Comment by popcornylu** [comment]
> > It seems that it requires every check view add the screenoshot logic. Could we add this feature as container?
> > ```
> > <ScreenshotBox>
> >    <QueryDataGrid />
> > </ScreenshotBox>
> > ```
> 
> Sure!

Here is the example
https://github.com/DataRecce/recce/pull/106

**Comment by kentwelcome** [comment]
Ultimately, I decided to wrap the <DataGrid> component by <ScreenshotDataGrid>.
The screenshot will only take on the <DataGrid> component. 

Due to the <DataGrid> having its scrolling logic. The header will keep showing on the top when the user scrolls the table.

If we use a <ScreenShotBox> or <Box> component to wrap up the <DataGrid> component, scrolling logic will be running on <Box>. This means the table's header won't be kept on the top of the screen.

When users take a screenshot, keeping the header on the top of the table will make the screenshot more readable.

**Pull request merged**
